const BaseAgent = require('./base-agent');
const path = require('path');
const logger = require('../utils/logger');

/**
 * Backend Engineer Agent
 * Generates API endpoints, business logic, database queries, and tests
 */
class BackendAgent extends BaseAgent {
  constructor(orchestrator) {
    super(
      orchestrator,
      'Backend-Agent',
      'docs/AI_WORKFORCE_SYSTEM.md' // Contains backend agent prompt
    );
  }

  /**
   * Execute a backend development task
   * Generates API code and creates a GitHub PR
   */
  async executeTask(taskPath) {
    try {
      const task = this.parseTaskFile(taskPath);
      if (!task) {
        logger.error(`${this.role}: Could not parse task file`);
        return false;
      }

      const taskId = task.metadata.id || path.basename(taskPath, '.md');
      
      logger.info(`${this.role}: Executing task ${taskId}`);
      await this.updateTaskProgress(taskPath, 'Analyzing requirements');

      // Generate code using OpenAI
      const codePrompt = this.buildCodeGenerationPrompt(task);
      const generatedCode = await this.generateArtifact(codePrompt);

      if (!generatedCode) {
        logger.error(`${this.role}: Failed to generate code`);
        return false;
      }

      await this.updateTaskProgress(taskPath, 'Code generated, preparing files');

      // Parse generated code into files
      const files = this.parseGeneratedCode(generatedCode);
      
      if (files.length === 0) {
        logger.error(`${this.role}: No files extracted from generated code`);
        return false;
      }

      logger.info(`${this.role}: Generated ${files.length} files`);

      // Create PR with generated code
      await this.updateTaskProgress(taskPath, 'Creating GitHub PR');
      
      const prTitle = `[${taskId}] ${task.metadata.title || 'Backend implementation'}`;
      const prBody = this.buildPRDescription(task, files);

      const pr = await this.createPR(taskId, files, prTitle, prBody);

      if (!pr) {
        logger.error(`${this.role}: Failed to create PR`);
        return false;
      }

      // Mark task complete
      await this.completeTask(taskPath, pr.url);

      return true;

    } catch (error) {
      logger.error(`${this.role}: Error executing task:`, error.message);
      return false;
    }
  }

  /**
   * Build prompt for code generation
   */
  buildCodeGenerationPrompt(task) {
    return `You are implementing a backend feature. Generate complete, production-ready code.

## Task Details
${task.content}

## Requirements
- Generate Express.js/Node.js API endpoints
- Include proper error handling
- Add input validation (use Zod if needed)
- Include JSDoc comments
- Follow REST conventions
- Generate corresponding tests

## Output Format
Provide the code in this exact format:

\`\`\`filename: path/to/file.js
// File content here
\`\`\`

Generate all necessary files:
1. Route handler file
2. Service/business logic file (if needed)
3. Test file
4. Any utility files needed

Start generating now:`;
  }

  /**
   * Parse generated code into file objects
   * Expects format: ```filename: path/to/file.js\ncode\n```
   */
  parseGeneratedCode(generated) {
    const files = [];
    const fileRegex = /```filename:\s*([^\n]+)\n([\s\S]*?)```/g;
    let match;

    while ((match = fileRegex.exec(generated)) !== null) {
      let filePath = match[1].trim();
      const content = match[2].trim();
      
      // Normalize path: remove leading slash, ensure forward slashes
      filePath = filePath.replace(/^[\\/]+/, '').replace(/\\/g, '/');
      
      // Skip empty content
      if (!content) {
        logger.warn(`${this.role}: Skipping empty file: ${filePath}`);
        continue;
      }
      
      files.push({
        path: filePath,
        content: content
      });
    }

    // If no files found with filename marker, try generic code blocks
    if (files.length === 0) {
      const codeBlockRegex = /```(?:javascript|js|typescript|ts)?\n([\s\S]*?)```/g;
      let blockMatch;
      let index = 0;

      while ((blockMatch = codeBlockRegex.exec(generated)) !== null) {
        const content = blockMatch[1].trim();
        if (content) {
          files.push({
            path: `packages/api/src/generated/code-${index++}.js`,
            content: content
          });
        }
      }
    }

    // Log files for debugging
    logger.info(`${this.role}: Parsed ${files.length} files: ${files.map(f => f.path).join(', ')}`);
    
    return files;
  }

  /**
   * Build PR description
   */
  buildPRDescription(task, files) {
    const fileList = files.map(f => `- ${f.path}`).join('\n');
    
    return `## Backend Implementation

**Task ID:** ${task.metadata.id || 'N/A'}

### Changes
${fileList}

### Description
${task.content.substring(0, 500)}${task.content.length > 500 ? '...' : ''}

### Generated by
Backend Agent (AI)

### Review Checklist
- [ ] Code follows project conventions
- [ ] Error handling is proper
- [ ] Input validation included
- [ ] Tests are comprehensive
- [ ] Documentation is clear

---
*This PR was automatically generated by the BuildPlan AI team.*`;
  }
}

module.exports = BackendAgent;
